[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
name = "langshell"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
async-trait = "0.1"
axum = { version = "0.8", features = [
  "http1",
  "http2",
  "json",
  # "macros",
  "matched-path",
  "tokio",
  "query",
], default-features = true }
base64 = "0.22"
ciborium = "0.2"
coset = "0.4"
futures = "0.3"
futures-util = "0.3"
http = "1.3"
parking_lot = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
sha3 = "0.11"
object_store = { version = "0.13" }
tokio-util = "0.7"
tokio = { version = "1", features = ["full"] }
structured-logger = "1"
tracing = { version = "0.1", features = ["kv_serde"] }
clap = { version = "4.6", features = ["derive", "env"] }
tower-http = { version = "0.6", features = ["compression-gzip", "cors"] }
markdown = "1"
mimalloc = { version = "0.1", features = ["v3"] }
rand = "0.10"
monty = "0.0"

[patch.crates-io]
monty = { git = "https://github.com/pydantic/monty.git", tag = "v0.0.17" }

[profile.release]
debug = false
lto = true
strip = true
opt-level = 'z'
codegen-units = 1
panic = "abort"
